"""create tabÃles debts

Revision ID: 2483e8243475
Revises: 
Create Date: 2022-12-09 21:58:50.135162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2483e8243475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devedor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divida',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('data_divida', sa.Date(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('devedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devedor_id'], ['devedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divida')
    op.drop_table('devedor')
    # ### end Alembic commands ###
