"""add join user / devedor

Revision ID: 7db70ebe2319
Revises: 607577d2840b
Create Date: 2022-12-20 18:24:30.687048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db70ebe2319'
down_revision = '607577d2840b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devedor', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devedor', 'usuario', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devedor', type_='foreignkey')
    op.drop_column('devedor', 'user_id')
    # ### end Alembic commands ###
