"""create tables

Revision ID: dfb01be1a7ad
Revises: 
Create Date: 2022-11-06 15:39:28.349142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb01be1a7ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devedor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divida',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('data_divida', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('vencimento', sa.DateTime(), nullable=True),
    sa.Column('devedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devedor_id'], ['devedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divida')
    op.drop_table('devedor')
    # ### end Alembic commands ###
